swagger: "2.0"
info:
  version: "1.0.0"
  title: "LeafCheck Model API"
  description: "An API for the LeafCheck model."

consumes:
  - "application/json"

produces:
  - "application/json"

basePath: "/api"

  